version: "3"
services:
  mysql:
    image: "wherehows/mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wherehows
  backend:
    image: "wherehows/backend:latest"
    ports:
      - "9001:9000"
    environment:
      WHZ_DB_USERNAME: wherehows
      WHZ_DB_PASSWORD: wherehows
      WHZ_DB_URL: jdbc:mysql://mysql:3306/wherehows?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=true
      PLAY_CRYPTO_SECRET: please_change_in_production_environment
    links:
      - "mysql:mysql"
  web:
    image: "wherehows/web:latest"
    ports:
      - "9000:9000"
    environment:
      WHZ_DB_USERNAME: wherehows
      WHZ_DB_PASSWORD: wherehows
      WHZ_DB_URL: jdbc:mysql://mysql:3306/wherehows?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=true
      PLAY_CRYPTO_SECRET: please_change_in_production_environment
    links:
      - "mysql:mysql"